from __future__ import annotations

import hashlib
import json
import os
import re
import secrets
import tempfile
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterator

_TOKEN_STORE_ENV = "GWAY_WEB_TOKEN_STORE"
_TOKEN_PREFIX = "gweb_v1"
_TOKEN_ID_PATTERN = re.compile(r"^[0-9a-f]{12}$")
_TOKEN_SECRET_PATTERN = re.compile(r"^[A-Za-z0-9_-]{43,}$")
_TOKEN_SECRET_BYTES = 32
_DEFAULT_TTL = 90 * 24 * 60 * 60


def _now() -> datetime:
    return datetime.now(timezone.utc)


def token_store_path() -> Path:
    configured = os.environ.get(_TOKEN_STORE_ENV)
    if configured:
        return Path(configured).expanduser()
    state_home = os.environ.get("XDG_STATE_HOME")
    if state_home:
        return Path(state_home).expanduser() / "gway-web" / "tokens.json"
    return Path.home() / ".local" / "state" / "gway-web" / "tokens.json"


@contextmanager
def _store_lock(path: Path | None = None) -> Iterator[None]:
    target = path or token_store_path()
    target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    target.parent.chmod(0o700)
    lock_path = target.with_name(f"{target.name}.lock")
    descriptor = os.open(lock_path, os.O_RDWR | os.O_CREAT, 0o600)
    try:
        os.fchmod(descriptor, 0o600)
        if os.name == "nt":
            import msvcrt

            os.write(descriptor, b"0") if os.fstat(descriptor).st_size == 0 else None
            os.lseek(descriptor, 0, os.SEEK_SET)
            msvcrt.locking(descriptor, msvcrt.LK_LOCK, 1)
        else:
            import fcntl

            fcntl.flock(descriptor, fcntl.LOCK_EX)
        yield
    finally:
        if os.name == "nt":
            import msvcrt

            os.lseek(descriptor, 0, os.SEEK_SET)
            msvcrt.locking(descriptor, msvcrt.LK_UNLCK, 1)
        else:
            import fcntl

            fcntl.flock(descriptor, fcntl.LOCK_UN)
        os.close(descriptor)


def _read_store(path: Path | None = None) -> dict[str, dict[str, object]]:
    target = path or token_store_path()
    if not target.exists():
        return {}
    try:
        payload = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    if not isinstance(payload, dict):
        return {}
    records = payload.get("tokens", {})
    return records if isinstance(records, dict) else {}


def _write_store(records: dict[str, dict[str, object]], path: Path | None = None) -> None:
    target = path or token_store_path()
    target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    target.parent.chmod(0o700)
    data = (json.dumps({"tokens": records}, indent=2, sort_keys=True) + "\n").encode(
        "utf-8"
    )
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{target.name}.", dir=target.parent
    )
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "wb", closefd=True) as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, target)
        target.chmod(0o600)
    except BaseException:
        try:
            os.close(descriptor)
        except OSError:
            pass
        temporary.unlink(missing_ok=True)
        raise


def _digest(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def _parse_scopes(scopes: str | tuple[str, ...]) -> tuple[str, ...]:
    values = scopes.split(",") if isinstance(scopes, str) else scopes
    cleaned = tuple(dict.fromkeys(value.strip() for value in values if value.strip()))
    if not cleaned:
        raise ValueError("at least one token scope is required")
    for value in cleaned:
        if ":" not in value or any(character.isspace() for character in value):
            raise ValueError(f"invalid token scope: {value}")
    return cleaned


def _token_id(token: str) -> str:
    parts = token.split("_", 3)
    valid = (
        len(parts) == 4
        and f"{parts[0]}_{parts[1]}" == _TOKEN_PREFIX
        and bool(_TOKEN_ID_PATTERN.fullmatch(parts[2]))
        and bool(_TOKEN_SECRET_PATTERN.fullmatch(parts[3]))
    )
    if not valid:
        raise ValueError(
            "token must be a high-entropy gweb_v1 bearer token generated by GWAY Web"
        )
    return parts[2]


def issue_token(
    *,
    name: str | None = None,
    scopes: str | tuple[str, ...] = "logs:read",
    ttl: int = _DEFAULT_TTL,
) -> dict[str, object]:
    if ttl <= 0:
        raise ValueError("token ttl must be greater than zero")
    selected_scopes = _parse_scopes(scopes)
    token_id = secrets.token_hex(6)
    secret = secrets.token_urlsafe(_TOKEN_SECRET_BYTES)
    token = f"{_TOKEN_PREFIX}_{token_id}_{secret}"
    created = _now()
    expires = created + timedelta(seconds=ttl)
    with _store_lock():
        records = _read_store()
        records[token_id] = {
            "name": name or token_id,
            "digest": _digest(token),
            "scopes": list(selected_scopes),
            "created_at": created.isoformat(),
            "expires_at": expires.isoformat(),
            "last_used_at": None,
            "revoked_at": None,
        }
        _write_store(records)
    return {
        "token_id": token_id,
        "name": name or token_id,
        "token": token,
        "scopes": list(selected_scopes),
        "expires_at": expires.isoformat(),
    }


def provision_token(
    token: str,
    *,
    name: str | None = None,
    scopes: str | tuple[str, ...] = "repo:read",
    ttl: int = _DEFAULT_TTL,
) -> dict[str, object]:
    """Idempotently register an externally held token while storing only its digest."""
    if ttl <= 0:
        raise ValueError("token ttl must be greater than zero")
    token_id = _token_id(token)
    selected_scopes = _parse_scopes(scopes)
    digest = _digest(token)
    now = _now()
    expires = now + timedelta(seconds=ttl)
    with _store_lock():
        records = _read_store()
        existing = records.get(token_id)
        if existing is not None:
            existing_digest = existing.get("digest")
            if not isinstance(existing_digest, str) or not secrets.compare_digest(
                existing_digest, digest
            ):
                raise ValueError(f"token id collision: {token_id}")
            if existing.get("revoked_at") is not None:
                raise ValueError(f"token is revoked: {token_id}")
            created_at = existing.get("created_at") or now.isoformat()
        else:
            created_at = now.isoformat()
        records[token_id] = {
            "name": name or (existing or {}).get("name") or token_id,
            "digest": digest,
            "scopes": list(selected_scopes),
            "created_at": created_at,
            "expires_at": expires.isoformat(),
            "last_used_at": (existing or {}).get("last_used_at"),
            "revoked_at": None,
        }
        _write_store(records)
    return {
        "token_id": token_id,
        "name": records[token_id]["name"],
        "scopes": list(selected_scopes),
        "expires_at": expires.isoformat(),
    }


def list_tokens() -> list[dict[str, object]]:
    records = _read_store()
    return [
        {
            "token_id": token_id,
            **{key: value for key, value in record.items() if key != "digest"},
        }
        for token_id, record in sorted(records.items())
    ]


def revoke_token(token_id: str) -> dict[str, object]:
    with _store_lock():
        records = _read_store()
        try:
            record = records[token_id]
        except KeyError as exc:
            raise KeyError(f"unknown token: {token_id}") from exc
        if record.get("revoked_at") is None:
            record["revoked_at"] = _now().isoformat()
            _write_store(records)
        revoked_at = record.get("revoked_at")
    return {"token_id": token_id, "revoked_at": revoked_at}


def verify_token(token: str, *, scope: str | None = None) -> bool:
    try:
        token_id = _token_id(token)
    except ValueError:
        return False
    records = _read_store()
    record = records.get(token_id)
    if record is None or record.get("revoked_at") is not None:
        return False
    digest = record.get("digest")
    if not isinstance(digest, str) or not secrets.compare_digest(
        digest, _digest(token)
    ):
        return False
    expires_at = record.get("expires_at")
    if not isinstance(expires_at, str):
        return False
    try:
        if datetime.fromisoformat(expires_at) <= _now():
            return False
    except ValueError:
        return False
    scopes = record.get("scopes", [])
    return scope is None or (isinstance(scopes, list) and scope in scopes)
